In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

print(np.arange(20).reshape(4,5))
np.arange(20).reshape(4,5).ndim

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


2

In [6]:
np.arange(20).reshape(-1,4,5)
'''
reshape 에서 -1은 해당 칸을 자동으로 계산
20을 n,4,5로 리쉐입하는데, n은 1이어야 값이 맞으니 1로 설정함
np.arange(21).reshape(2,-1) 처럼 어떻게도 값이 남거나 부족하면 오류
'''

'\nreshape 에서 -1은 해당 칸을 자동으로 계산\n20을 n,4,5로 리쉐입하는데, n은 1이어야 값이 맞으니 1로 설정함\nnp.arange(21).reshape(2,-1) 처럼 어떻게도 값이 남거나 부족하면 오류\n'

In [17]:
import requests
from xml.etree import ElementTree as ET

url = f"https://m.stock.naver.com/front-api/external/chart/domestic/notice?symbol=010140&startTime=20141017&endTime=20150702&requestType=0"



In [28]:
'''
ET.fromstring(data)
ET.fromstring() 함수는 XML 형식의 문자열(data)을 파싱(분석)하여 XML 트리의 루트 요소(root element)를 생성합니다.
반환된 root는 XML 문서의 최상위 요소(Element) 객체이며, 이 객체를 통해 XML 내부의 태그, 속성, 자식 요소 등에 접근할 수 있습니다
'''
data = requests.get(url).text
with open('./xml파일 구조.txt', 'w', encoding='utf-8') as f:
    f.write(data)
root = ET.fromstring(data)

In [21]:
'''
ET에서 제공하는 iter는 조건을 만족하는 모든 요소를 반복하는 제네레이터를 반환(한 번 사용하면 삭제)
'''
items = root.iter(tag='item')
total1 = []
for i in items:
    for x in i:
        total1.append({i.get('date'), x.text})

In [22]:
'''
방법2 : 한줄에 넣음
'''
total2 = [{'date' : i.get('date'), 'information' : x.text} for i in root.iter(tag='item')  for x in i]

In [27]:
import pandas as pd
pd.DataFrame(total).to_csv("./total1.csv", index=False, encoding='utf-8-sig')
pd.DataFrame(total2).to_csv("./total2.csv", index=False, encoding='utf-8-sig')