In [1]:
from IPython.display import Image

In [2]:
%matplotlib inline

In [3]:
Image(url='https://raw.githubusercontent.com/rickiepark/ml-with-pytorch/main/ch15/figures/15_01.png', width=500)

In [4]:
Image(url='https://raw.githubusercontent.com/rickiepark/ml-with-pytorch/main/ch15/figures/15_02.png', width=500)

In [5]:
Image(url='https://raw.githubusercontent.com/rickiepark/ml-with-pytorch/main/ch15/figures/15_03.png', width=500)

In [6]:
Image(url='https://raw.githubusercontent.com/rickiepark/ml-with-pytorch/main/ch15/figures/15_04.png', width=500)


In [9]:
import torch 
import torch.nn as nn

In [11]:
torch.manual_seed(1)
rnn_layer = nn.RNN(input_size=5, hidden_size=2, num_layers=1, batch_first=True)

In [14]:
w_xh = rnn_layer.weight_ih_l0
w_hh = rnn_layer.weight_hh_l0
b_xh = rnn_layer.bias_ih_l0
b_hh = rnn_layer.bias_hh_l0

In [15]:
w_xh

Parameter containing:
tensor([[ 0.3643, -0.3121, -0.1371,  0.3319, -0.6657],
        [ 0.4241, -0.1455,  0.3597,  0.0983, -0.0866]], requires_grad=True)

In [18]:
print("w_xh 크기" , w_xh.shape)
print("w_hh 크기" , w_hh.shape)
print("b_xh 크기" , b_xh.shape)
print("b_hh 크기" , b_hh.shape)

w_xh 크기 torch.Size([2, 5])
w_hh 크기 torch.Size([2, 2])
b_xh 크기 torch.Size([2])
b_hh 크기 torch.Size([2])


In [24]:
x_seq = torch.tensor([[1.0]*5, [2.0]*5, [3.0]*5] ).float()
x_seq.shape

torch.Size([3, 5])

In [25]:
x_seq.reshape(-1,3,5).shape

torch.Size([1, 3, 5])

In [27]:
output, hn = rnn_layer(x_seq.reshape(-1,3,5))

In [ ]:
out_manual = []
for t in range(3):
    xt = torch.reshape(x_seq[t], (1,5))
    print(f"타임 스텝 {t} --> ")
    print("입력    : ", xt.numpy())
   
    ht = torch.matmul(xt, torch.transpose(w_xh, 0, 1)) + b_xh
    print(" 은닉  : ", ht.detach().numpy())

    if t>0:
        prev_h = out_manual[t-1]
    else:
        prev_h = torch.zeros((ht.shape))

    ot = ht + torch.matmul(prev_h, torch.transpose(w_hh, 0, 1)) + b_hh
    ot = torch.tanh(ot)
    out_manual.append(ot)
    print ("  출력(수동)   : ", ot)
    print ("  RNN 모듈에서 계산된 값 : ", output[:, t].detach().numpy())

타임 스텝 0 --> 
입력    :  [[1. 1. 1. 1. 1.]]
 은닉  :  [[-0.4701929  0.5863904]]
  출력(수동)   :  tensor([[-0.3520,  0.5253]], grad_fn=<TanhBackward0>)
  RNN 모듈에서 계산된 값 :  [[-0.3519801   0.52525216]]
타임 스텝 1 --> 
입력    :  [[2. 2. 2. 2. 2.]]
 은닉  :  [[-0.88883156  1.2364397 ]]
  출력(수동)   :  tensor([[-0.6842,  0.7607]], grad_fn=<TanhBackward0>)
  RNN 모듈에서 계산된 값 :  [[-0.68424344  0.76074266]]
타임 스텝 2 --> 
입력    :  [[3. 3. 3. 3. 3.]]
 은닉  :  [[-1.3074702  1.8864892]]
  출력(수동)   :  tensor([[-0.8649,  0.9047]], grad_fn=<TanhBackward0>)
  RNN 모듈에서 계산된 값 :  [[-0.8649416  0.9046636]]


In [32]:
ot

tensor([[-0.3520,  0.5253]], grad_fn=<TanhBackward0>)

In [33]:
output

tensor([[[-0.3520,  0.5253],
         [-0.6842,  0.7607],
         [-0.8649,  0.9047]]], grad_fn=<TransposeBackward1>)

In [37]:
import konlpy

In [ ]:
import jdk
import konlpy

In [44]:
jdk.install(version=17)

'/home/user1/.jdk/jdk-17.0.15+6'